name: eunice_ui
description: UI Toolkit for the Eunice Hong Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 6.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  very_good_analysis: 5.1.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  line_length: 80
  assets:
    package_parameter_enabled: true